---
title: "Aula 01 de R"
author: "Prof. Leticia Raposo"
date: "23 de agosto de 2019"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Aprendendo a mexer no R

## Primeira etapa:

Baixar o arquivo presente no link <https://leticiaraposo.netlify.com/bioestatisticacabn>.

**Atenção!** *Apenas baixar e não abrir!*

```{r}
getwd() # verificar o diretorio atual
setwd("C:/Users/Leticia/Desktop") # definir o diretorio

data(iris) # carrega banco de dados do R
iris

iris[1,] # pega a primeira linha
iris[1:10,] # pega da primeira à décima linha
iris[c(1,10,20,50),] # pega as linhas 1, 10, 20 e 50

iris[,1] # pega a primeira coluna
iris[,1:3] # pega as colunas de 1 a 3
iris[,c(1,3)] # pega as colunas 1 e 3

iris2 <- iris[1:50, c(1,3)] # pega as primeiras 50 linhas e as colunas 1 e 3

iris3 <- iris[iris$Species == "versicolor",] # pega todas as linhas que possuem a classe versicolor em Species

str(iris) # vê a estrutura dos dados 
iris$Species # vê a variável Species
```

