---
title: "Biomedicina e Ciência Biológicas"
---

<br>
<i>O objetivo do curso é apresentar um conjunto de métodos estatísticos que permitam ao estudante ler, 
compreender e interpretar os trabalhos técnicos e científicos que se utilizam da Estatística, assim 
como  ter  uma  noção  das  técnicas  envolvidas  na  coleta,  apresentação,  análise  e  interpretação  de 
dados tanto na área de planejamento, como na de pesquisa.</i> 
<br>
<br>

As aulas são ministradas nas quintas e sextas, das 9h às 12h.

<ul class="fa-ul">
<li><i class="far fa-calendar-alt"></i> *Quinta-feira*: Sala 301N
<li><i class="far fa-calendar-alt"></i> *Sexta-feira*: Laboratório 3
</ul>
<br>

<h4 style="color:rgb(235, 104, 100);">Material Didático</h4>

<ul class="fa-ul">
<li><i class="fas fa-book"></i> DANCEY, Christine P.; REIDY, John G.; ROWE, Richard. **Estatística Sem Matemática para as Ciências da Saúde**. Penso Editora, 2017.
<li><i class="fas fa-book"></i> MAGNUSSON, Willian E. **Estatística [sem] matemática: a ligação entre as questões e a análise**. Planta, 2003.
<li><i class="fas fa-book"></i> BARBETTA, Pedro Alberto. **Estatística aplicada às ciências sociais**. Ed. UFSC, 2008.
</ul>

<br>

<h4 style="color:rgb(235, 104, 100);">Conteúdo Programático</h4>

**PARTE I – UMA INTRODUÇÃO AO PROCESSO DE PESQUISA**
<br>

+ Aula 1 - Pesquisas e Dados: [Slides](https://drive.google.com/file/d/1ryuqE4gLU28KXwcDMm8717D3eqEQ2QzO/view?usp=sharing)
+ Aula 2 - Introdução ao R / RStudio: [Apostila (em inglês)](https://drive.google.com/file/d/1V4p9P3a1r6bijyIgy-mWYDjKa1SMXeFb/view?usp=sharing), [Script de Instalação de Pacotes]()

**PARTE II – ESTATÍSTICA DESCRITIVA**
<br>

+ Aula 3 - Estatística Descritiva Univariada:
+ Aula 4 - Estatística Descritiva Bivariada:

**PARTE III – ESTATÍSTICA PROBABILÍSTICA**
<br>

+ Aula 5 - Introdução à Probabilidade
+ Aula 6 - Variáveis Aleatórias e Distribuições de Probabilidade

**PARTE IV – ESTATÍSTICA INFERENCIAL**
<br>

+ Aula 7 - Amostragem
+ Aula 8 - Estimação de Parâmetros
+ Aula 9 - Testes de Hipóteses I
+ Aula 10 - Testes de Hipóteses II
+ Aula 11 - Testes de Hipóteses III

**PARTE VI – MODELOS LINEARES GENERALIZADOS**
<br>

+ Aula 12 - Modelos de Regressão Simples e Múltipla
+ Aula 13 - Modelos de Regressão Logística

<br>

<h4 style="color:rgb(235, 104, 100);">Materiais Complementares</h4>

- Checklists: [Análise Exploratória](https://drive.google.com/file/d/1Wdi--khEKj_o5cBQ0p4wkkSLwknPJMp5/view?usp=sharing), [Artigo Científico](https://drive.google.com/file/d/1nuzRCB74EXmpIpCf4jDX4xnqaJNaG0wN/view?usp=sharing)
- Dicas: [Elaboração de Questionário](https://drive.google.com/file/d/1BCTrFEdOF-Ek_sNz-tZ4WhS9PQDR9xSf/view?usp=sharing)
- Funçoes do R: [Estatística Descritiva](https://drive.google.com/file/d/1KU2ZbYE2xODTQ5bi0kyeXblimNCqI29o/view?usp=sharing)
- Tutoriais: [Instalando R e RStudio](https://drive.google.com/file/d/1LDRC0d5Q-5GXkVrp8OzPyIXykJxfCOMF/view?usp=sharing)

<br>

<h4 style="color:rgb(235, 104, 100);">Avaliação</h4>

A avaliação do aluno na disciplina será realizada por meio de duas atividades (AT), duas avaliações (AV) e um trabalho final (TF) dividido em parte escrita (TFE) e oral (TFO).
A nota final será calculada da seguinte forma:

$$Nota Final = \frac{AT1 + AT2 + AV1 + AV2 + (0.6*TFEscrita + 0.4TFO)}{5}$$


